#!/bin/bash
cd ~/Developer
LS=$(ls)
let COUNTER=1
for ITEM in $LS
do
	echo [${COUNTER}] $ITEM;
	((COUNTER++))
done

echo -e '\n'

if [ $1 ]
	then
		sleep 1;
		IN=$1
	else
		read -p "Folder to go (default ~/Developer): "$'\n' IN
fi


COUNTER=1
for ITEM in $LS
do
	if [ $COUNTER -eq $IN ]
		then
			cd $ITEM;
	fi
	((COUNTER++));
done
clear
$SHELL
